version: '3'
services:
  nginx:
    ports:
      - "3000:80"
  node_app:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=root 
      - MONGO_PASSWORD=passerty
      - SESSION_SECRET=secret_node@12
    command: yarn dev

  mongo: 
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root 
      - MONGO_INITDB_ROOT_PASSWORD=passerty