version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node_app:
    build: .
    # ports:
    #   - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo
  
  mongo: 
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root 
      - MONGO_INITDB_ROOT_PASSWORD=passerty
    volumes:
      - type: volume
        source: mongo-db
        target: /data/db
  
  redis: 
    image: redis
    ports:
      - "6379:6379"

volumes:
  mongo-db: